version: '3.0'

expectations:
 population_size: 1000

actions:

  generate_dataset:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv
    ## note: when running studies for real it is recommended to add the option --output-format='csv.gz' to the run command,
    ## and add '.gz' to the output file path, to produce the output in compressed form to reduce file size.

  # describe: 
  #   run: r:latest analysis/report.R
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/descriptive.png
